### ISSUE TITLE
Switch to using K3s for CI instead of RKE

### ISSUE THREAD

**Issue by brandond** [k3s-io/helm-controller#104]
Once https://github.com/k3s-io/k3s/issues/1445 is closed, we should switch CI over to using a build of K3s in Docker to test helm-controller, instead of using RKE1 as we currently do. This would provide a more directly comparable environment to how helm-controller is most frequently run.

**Comment by rancher-max** [comment]
CI can be switched over now whenever as I've closed the mentioned issue

**Comment by dweomer** [comment]
Should we consider [kind](https://kind.sigs.k8s.io/)?
