### ISSUE TITLE
Doc on the helmchart CRD

### ISSUE THREAD

**Issue by sgandon** [k3s-io/helm-controller#115]
hello,
is there any documentation explaining the attributes in the helmchart crd ?
I found the struct here https://github.com/k3s-io/helm-controller/blob/4d509b9edd709e46c50ce9ac9dfb9c8960459376/pkg/apis/helm.cattle.io/v1/types.go#L19
but that would be nice to have some explaination on to what each attribute does.
Any idea on what the `jobImage` does for instance ?

**Comment by bdsoha** [comment]
@sgandon Have a look here https://docs.k3s.io/helm#helmchart-field-definitions

**Comment by sgandon** [comment]
Thanks a lot for your answer.
I'll close the ticket.
