### ISSUE TITLE
Using Helm controller to initialise cilium

### ISSUE THREAD

**Issue by PurpleBooth** [k3s-io/helm-controller#151]
We're using the Helm Controller to initialise cilium, and we'd like to use `node.cilium.io/agent-not-ready` to prevent scheduling on the nodes before cilium is ready using initial taints. However this prevents the `bootstrap: true` flag from working. What is the best way to achieve this?

We'd like to avoid having to restart any unmanaged containers. If needed I could try submitting a PR allowing the customisation of the taint tolerations, but I don't want do that if it's not a direction you'd like to go in.

(Kinda hoping there's a cool feature I have missed to avoid this all together 😄 )

**Comment by mysticaltech** [comment]
@brandond Any ideas on the above? Our Cilium deployment on Kube-Hetzner is not working correctly, and we need to know what to do ASAP, please. Guidance would be genuinely appreciated 🙏

**Comment by brandond** [comment]
@PurpleBooth there isn't a good way to add arbitrary tolerations to the controller at the moment, no. Is the NotReady state on the kubelet that's present until the CNI comes up not sufficient for what you're trying to do? You need to inject another taint that mirrors the kubelet's CNI deployment status?

@mysticaltech your ask seems to be unrelated do what @PurpleBooth is trying to accomplish; I'm not sure what kube-hetzner has to do with k3s or our helm-controller.

**Comment by mysticaltech** [comment]
@brandond We use both! Thanks for the details. Will let @PurpleBooth answer her part.

**Comment by danielkza** [comment]
I ran into what I believe is a variant of the same issue today, but in a different situation. I made a mistake while deploying the configuration for the rke2-cilium chart which took down Cillium agent in my single node, but now the helm-install pod cannot run due to the `agent-not-ready` taint even after I corrected the chart configuration.

It would be really helpful to manage the tolerations for the controller and the pods it generates, and ship sensible defaults in K3S/RKE2 stop avoid such "lock out" situations.

**Comment by brandond** [comment]
> now the helm-install pod cannot run due to the agent-not-ready taint

The CNI HelmCharts are bootstrap charts, which run with host network and tolerate most things, including the NotReady taint. Are you sure this is the root cause of the failure to recover?

https://github.com/k3s-io/helm-controller/blob/f9103f66197ade3a06f4d48c9ea85f48d8c1ff1e/pkg/controllers/chart/chart.go#L525-L553

**Comment by danielkza** [comment]
@brandond I believe so, I see a pending helm install pod like such:

```
$ kubectl --kubeconfig ~/.kube/rke2_config get event --namespace kube-system --field-selector involvedObject.name=helm-install-rke2-cilium-zwdfb
LAST SEEN   TYPE      REASON             OBJECT                               MESSAGE
28m         Warning   FailedScheduling   pod/helm-install-rke2-cilium-zwdfb   0/1 nodes are available: 1 node(s) had untolerated taint {node.cilium.io/agent-not-ready: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
```

I took a stab at adding support for customizing tolerations:  https://github.com/k3s-io/helm-controller/pull/221

**Comment by brandond** [comment]
Oh... why does cilium add a custom not-ready taint? that's dumb. The existing kubelet not-ready taint should cover the CNI not being initialized.

**Comment by brandond** [comment]
cc @thomasferrandiz @rbrtbnfgl in case y'all have notes on how to best pass this through to the cilium subchart.

**Comment by danielkza** [comment]
@brandond thanks for the recommendation, I will try to add the operator arguments and see if it solves my problem.

**Comment by qasmi** [comment]
Hello,

I am encountering a similar issue but with a different use case. I added the `CriticalAddonsOnly=true:NoExecute` taint to my master nodes (as recommended [[here](https://docs.rke2.io/install/ha?_highlight=criticaladdonsonly#2a-optional-consider-server-node-taints)]).

I assumed that the `helm-controller` would tolerate this taint, as described [[here](https://github.com/k3s-io/helm-controller/blob/v0.16.5/pkg/controllers/chart/chart.go#L607C5-L609C41)].

However, I ended up with a pending job created by the `helm-controller`, which only has the following tolerations:

```yaml
tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
```

Am I missing something here?

**Comment by brandond** [comment]
Only bootstrap charts tolerate the taint you've added:

https://github.com/k3s-io/helm-controller/blob/38f4782e9625252befafc6234dcf9118acc5a73d/pkg/controllers/chart/chart.go#L589-L621

**Comment by qasmi** [comment]
@brandond thanks for your answer.
Is there a way to override the securityContext of the created job in the config ?  

As a last escape, I'm considering using a Kyverno mutating policy to modify it at runtime, but I'm not very fan of this approach!

**Comment by brandond** [comment]
Why do you need to modify the securitycontext?

**Comment by qasmi** [comment]
@brandond I just updated the comment, it was a mistake.

**Comment by brandond** [comment]
You cannot directly set the tolerations. You can however tolerate most common taints by setting `bootstrap: true` in the HelmChart spec, as I suggested above.
