### ISSUE TITLE
crd.yml is missing

### ISSUE THREAD

**Issue by headcheater** [k3s-io/helm-controller#163]
upload crd.yml, please.

**Comment by brandond** [comment]
It is included in both of the release artifacts:
* https://github.com/k3s-io/helm-controller/releases/download/v0.13.0/deploy-cluster-scoped.yaml
* https://github.com/k3s-io/helm-controller/releases/download/v0.13.0/deploy-namespaced.yaml

**Comment by headcheater** [comment]
Thanks
