### ISSUE TITLE
Helmchart install/upgrade fails on HelmVersion check

### ISSUE THREAD

**Issue by elcomtik** [k3s-io/helm-controller#165]
The newest Traefik helm chart uses version check for helm used https://github.com/traefik/traefik-helm-chart/blob/a85ab3843221ff3dd7dc87249d6963b14e6ba3fb/traefik/templates/deployment.yaml#L2-L4.

I have a deployment of this chart on the latest stable k3s cluster. I tried to upgrade this chart from the older version by updating the helm chart manifest managed by helm-controller. It failed on this check.

I'm not sure what version of the helm is actually used by this controller, I tried to search for this info in a codebase with no success.

Any idea how to solve this issue?

**Comment by brandond** [comment]
What version of K3s are you using?

**Comment by brandond** [comment]
Each K3s release tells you what helm-controller version it has. From there you can look at the job image, and see what version of Helm it has: https://github.com/k3s-io/klipper-helm/blob/v0.7.3-build20220613/package/Dockerfile#L6.

We could perhaps consider putting that in the release notes, but to answer the question, that k3s release ships with v3.8.1. The release coming out later this week will include v3.10.2.

**Comment by elcomtik** [comment]
> Each K3s release tells you what helm-controller version it has. From there you can look at the job image, and see what version of Helm it has: 
> * https://github.com/k3s-io/helm-controller/blob/v0.13.0/pkg/controllers/chart/chart.go#L56
> * https://github.com/k3s-io/klipper-helm/blob/v0.7.3-build20220613/package/Dockerfile#L6.

Obviously I didn't searched enough 😂

> We could perhaps consider putting that in the release notes, but to answer your question, that k3s release ships with v3.8.1. The release coming out later this week will include v3.10.2.

That would be great. I'm looking forward to thus release.
