### ISSUE TITLE
Facilitate DCO in GitHub web UI

### ISSUE THREAD

**Issue by Bert-R** [k3s-io/helm-controller#171]
Given that DCO is mandatory, you might want to enable check the box "Require contributors to sign off on web-based commits"  on this repo, as described here: https://github.com/todogroup/gh-issues/issues/50#issuecomment-1148657762

That prevents an issue like I just ran into: #170

**Comment by brandond** [comment]
cc @cwayne18

**Comment by cwayne18** [comment]
Sorry for missing this :| 
<img width="712" alt="image" src="https://github.com/k3s-io/helm-controller/assets/1471943/7b5a8962-c27e-497c-a59c-014245275382">
