### ISSUE TITLE
Is it possible to specify options --reuse-values, --reset-values?

### ISSUE THREAD

**Issue by ahebibovic** [k3s-io/helm-controller#174]
https://github.com/k3s-io/helm-controller/blob/master/pkg/apis/helm.cattle.io/v1/types.go#L32

I guess it can be done like this: https://github.com/k3s-io/helm-controller/pull/143

Thanks!

**Comment by brandond** [comment]
No, but I'm not sure these options would really be necessary, since all the values are persisted in the HelmChart and HelmChartValues resources themselves... given that the values are persisted externally, what would the use case be for using those options?

**Comment by ahebibovic** [comment]
I am going to use that from there. Thanks!

**Comment by oivindoh** [comment]
A use-case I can think of is if there's an issue with an image used by a helm chart, so you've overridden the image in your HelmChartConfig, but then the project releases a new chart version that points to a fixed image and you want to go back to using whichever image the chart specifies. Currently the previous value is sticky unless you explicitly set a new one, so new defaults are impossible to apply.

**Comment by brandond** [comment]
> so you've overridden the image in your HelmChartConfig, but then the project releases a new chart version that points to a fixed image and you want to go back to using whichever image the chart specifies. Currently the previous value is sticky unless you explicitly set a new one, so new defaults are impossible to apply.

I don't believe that's true. The `helm upgrade` command is not run with `--reuse-values`, so if you remove the value from your HelmChartConfig, the chart will be redeployed without your custom value, and go back to using the chart default.
