### ISSUE TITLE
repoCA as a secret reference

### ISSUE THREAD

**Issue by poblin-orange** [k3s-io/helm-controller#187]
helm contoller enables setting corporate ca in pem format.
However, is format is not really convenient (expects clear text pem, whereas this type cert is usually managed as base64 encoded secret data).
Offering secretRef, or local fs would be helpfull.

**Comment by brandond** [comment]
> this type cert is usually managed as base64 encoded secret data

When storing certs+keys for a `kubernetes.io/tls` type secret, yes. However, TLS secrets **require** both a cert and key, and it most cases it wouldn't be appropriate for a client (Helm in this case) to have access to the key. And if you don't need to store the key, then why are you using a secret to store the public certificate?

We may add this when we add support for a SecretRef for registry auth, but tbh I don't really see why you would want to keep a cert in a secret.

**Comment by poblin-orange** [comment]
Hi @brandond 
Agreed in that case we should use on Opaque type Secret.
For instance, fluxcd Notification has this type of cross ref. https://fluxcd.io/flux/components/notification/provider/#example-1

My use case is the following:
- im deploying a k3s cluster in a edge environment, with kairos.io  https://kairos.io/docs/advanced/build/
- to have it auto installed, im using k3s HelmChart, referencing a corporate helm repo.

The helm repo and caRepo need to be fed in the kairos cloud-config file. In that context, escaping multi-line ca cert is unpractical (see https://kairos.io/docs/advanced/build/#build-a-cloud-image)
On the other hand, i could easily feed the caRepo with the single line base64 encoded value from my master cluster.

**Comment by brandond** [comment]
I still don't think a secret is the right place for it, if anything it should be in a separate configmap, similar to the `kube-root-ca.crt` configmap that is injected into namespaces. If it doesn't have a confidential component (no private key) it belongs in a configmap, not a secret.

**Comment by poblin-orange** [comment]
I guess its a matter of taste. My aim is to avoid inlining the ca cert in the HelmChart CR definition, so a configMap reference would be ok for me :-)
