### ISSUE TITLE
modified helm install-job using the k8s dynamic admission controller by injecting some custom labels and annotations into it, causing the Helm Controller is error syncing constantly requeuing

### ISSUE THREAD

**Issue by lingbohome** [k3s-io/helm-controller#188]
version: 0.12.3
the helm-install-job is constantly being deleted and rebuilt.
logs:
`2023-04-24T03:47:33.121140867Z time="2023-04-24T03:47:33Z" level=error msg="error syncing 'demo0/hu002': handler helm-controller: DesiredSet - Replace Wait batch/v1, Kind=Job demo0/helm-install-hu002 for helm-controller demo0/hu002, requeuing`

this is not the case with the helm-delete job, which can be modified by the k8s dynamic admission Controller and run normally until completion.

Is this a normal phenomenon? Or is there a way around it?

**Comment by brandond** [comment]
Yeah, the DesiredSet Apply code in the helm controller will see that the Job spec differs from the spec it is expecting, and will continue to apply the changes over and over again until the spec is in sync with what it wants.

What exactly is your admission controller changing on the Job? Do you have the option to exclude the helm controller jobs from being modified?
