### ISSUE TITLE
Fix missing escape for IPv6 support.

### ISSUE THREAD

**Issue by frederictobiasc** [k3s-io/helm-controller#204]
Hi. I opened a PR with a fix in the `klipper-helm` repo. 
I don't know if anyone is actively monitoring the PRs there, therefore I just wanted to ping here, so you can check it out.

https://github.com/k3s-io/klipper-helm/pull/71

**Comment by manuelbuil** [comment]
HI @frederictobiasc. Thanks for contributing and sorry for ignoring you! We normally track everything k3s related in the k3s repo. Could you create an issue there describing the error you are seeing and then, in the PR, paste the link to that issue? Adding the error in the PR is also helpful for QA to verify that your PR fixes it :)

**Comment by manuelbuil** [comment]
hey, are you still interested in contributing?

**Comment by frederictobiasc** [comment]
Hi, absolutely!
I thought that would be unnecessary, since @brandond already approved my PR!
I just created the issue: https://github.com/k3s-io/k3s/issues/9499

**Comment by frederictobiasc** [comment]
Closing this since it was just merged.
