### ISSUE TITLE
How to install the klipper helm chart

### ISSUE THREAD

**Issue by SarthakNarayan** [k3s-io/helm-controller#206]
I have a k8s cluster and I want to install klipper load balancer on it. How can I do this? I don't see any manifests or helm charts for installing klipper. There is this GitHub URL (https://github.com/k3s-io/klipper-helm) , but I don't know how to use it.

**Comment by brandond** [comment]
See the example deployment yamls in the release artifacts: https://github.com/k3s-io/helm-controller/releases

**Comment by samcday** [comment]
@brandond what do you think about extracting the ServiceLB functionality into a standalone controller?

I was able to hack something together in a couple of hours: https://github.com/samcday/servicelb-standalone

I just copied the [servicelb.go](https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/servicelb.go) + [cloudprovider.go](https://github.com/k3s-io/k3s/blob/master/pkg/cloudprovider/cloudprovider.go) into a new project, hacked in a simple `main.go` entrypoint, and wrapped it in a hacked up Helm chart.

If I understand correctly, the servicelb reconciliation once existed as an independent controller but was moved into the cloudprovider to simplify it a bit. Personally, I hate the cloud-provider pattern and hope it eventually goes away (in favour of just writing a proper controller using controller-runtime). But I get the logic behind trying to reduce code and maintenance burden, of course :) But anyway, a cloudprovider can just implement ensureLB and nothing else (as proven by the linked standalone hackjob).
