### ISSUE TITLE
Missing documentation for HelmChart and other API objects 

### ISSUE THREAD

**Issue by SohamG** [k3s-io/helm-controller#212]
I couldn't find documentation for all the available/significant keys for `kind: HelmChart`. Currently the best way seems to be to read the [source code](https://github.com/k3s-io/helm-controller/blob/master/pkg/apis/helm.cattle.io/v1/types.go)

Possible fix is to flesh out the example manifest file with all possible keys (a la values.yml)

**Comment by brandond** [comment]
Have you seen: https://docs.k3s.io/helm#helmchart-field-definitions

**Comment by SohamG** [comment]
Oh, my apologies. I am using RKE2 (also from Rancher labs) and the docs there sent me here, and so did some cursory google searches. Perhaps that link deserves a place in the readme.

Closing

**Comment by brandond** [comment]
Rke2 docs also cover the fields, although they may not be as up to date with some new additions.
https://docs.rke2.io/helm#helmchart-field-definitions
