### ISSUE TITLE
No status in HelmChart can reflect the deploying status of a chart

### ISSUE THREAD

**Issue by yeahdongcn** [k3s-io/helm-controller#217]
I'm using `HelmChart` to install harbor in my kind cluster, but I can't see the deploying status by `kubectl --kubeconfig=kubeconfig.yaml get helmcharts -A -o yaml`.

```yaml
apiVersion: v1
items:
- apiVersion: helm.cattle.io/v1
  kind: HelmChart
  metadata:
    annotations:
      helmcharts.cattle.io/managed-by: helm-controller
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"helm.cattle.io/v1","kind":"HelmChart","metadata":{"annotations":{},"name":"harbor","namespace":"kube-system"},"spec":{"chart":"harbor","repo":"https://helm.goharbor.io","targetNamespace":"harbor"}}
    creationTimestamp: "2023-12-18T07:17:44Z"
    finalizers:
    - wrangler.cattle.io/on-helm-chart-remove
    generation: 3
    name: harbor
    namespace: kube-system
    resourceVersion: "696"
    uid: d284d25a-a7a8-4f32-924b-b7c930f8f3df
  spec:
    chart: harbor
    repo: https://helm.goharbor.io
    targetNamespace: harbor
  status:
    jobName: helm-install-harbor
kind: List
metadata:
  resourceVersion: ""
```

Expected behavior:
I can see the status of the actual deployment status of helm charts.

**Comment by brandond** [comment]
The embedded helm controller is very basic, and just triggers runs of the helm CLI tool to when fields on the CRs change. The controller itself intentionally does not interact directly with the chart or any installed releases, nor does it mirror the release status. If you have needs beyond what the embedded helm controller provides, there are several other projects available that provide more in-depth intergration.

**Comment by yeahdongcn** [comment]
> there are several other projects available that provide more in-depth integration.

@brandond Could you please list any names for it? Thanks.

**Comment by brandond** [comment]
Flux and Argo both have Helm support, as does Fleet if you are using Rancher.
