### ISSUE TITLE
feat: add `ownerReferences` in the applied resources.

### ISSUE THREAD

**Issue by hsblhsn** [k3s-io/helm-controller#243]
Hi,
Technically the `HelmChart` field is the owner of all the resources the chart is going to apply. So I believe the controller should add an entry referencing the `HelmChart` into the `ownerReferences`.

Please let me know what do you think.

**Comment by brandond** [comment]
This controller doesn't actually create resources. It just runs the `helm` CLI tool to create things, and there is no way to tell Helm to add an arbitrary resource as the owner of resources created by the chart.

Also - charts may deploy resources to multiple namespaces, or create resources that are not namespaced. Owner references cannot be cross-namespace:
> Dependent objects have a metadata.ownerReferences field that references their owner object. A valid owner reference consists of the object name and a [UID](https://kubernetes.io/docs/concepts/overview/working-with-objects/names) within the same [namespace](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces) as the dependent object.

Given that, owner reference would not work anyway for any case where the created resources are in a different namespace than the HelmChart resource.
