### ISSUE TITLE
[DOC] What version of Helm chart is supported?

### ISSUE THREAD

**Issue by gbonnefille** [k3s-io/helm-controller#37]
What is the version of Helm chart supported (2 or 3)?
Perhaps such information can be added in the README.

**Comment by davidnuzik** [comment]
Helm v2 / v3 info is currently documented here: https://rancher.com/docs/k3s/latest/en/helm/
If this is not sufficient let me know what you would like to change and we can reopen the issue.

**Comment by davidnuzik** [comment]
Closed by mistake.
