### ISSUE TITLE
Support git repositories as helm repository

### ISSUE THREAD

**Issue by mamiu** [k3s-io/helm-controller#69]
As the title says: support git repositories as helm repository or as a separate (helm repository independent) chart source because some chart repos have no `index.yaml` file (e.g. [rancher/charts](https://github.com/rancher/charts) or [rancher/system-charts](https://github.com/rancher/system-charts) as pointed out [here](https://github.com/rancher/rancher/issues/16449#issuecomment-435777340) and [here](https://github.com/rancher/rancher/issues/16449#issuecomment-441692503)).

Rancher for example is able to do that:

<img width="959" alt="Screen Shot 2020-10-22 at 15 46 12" src="https://user-images.githubusercontent.com/3653465/96829867-c431d600-147d-11eb-8bb3-65d41c954fac.png">

Here's the default `rancher/charts` repo:

<img width="821" alt="Screen Shot 2020-10-22 at 15 42 12" src="https://user-images.githubusercontent.com/3653465/96829893-cd22a780-147d-11eb-8821-d9feb7ded0db.png">

**Comment by deveshk0** [comment]
Any plans to support this?

**Comment by mamiu** [comment]
It seems like that this feature was implemented in the meantime:

https://rancher.com/docs/k3s/latest/en/helm/#helmchart-field-definitions
