### ISSUE TITLE
How to change helm controller configuration in k3s - use newer klipper-helm image?

### ISSUE THREAD

**Issue by ieugen** [k3s-io/helm-controller#79]
Hello,

I'm running a k3s cluster and using helm controller to install some charts.
I would like to upgrade the klipper-helm image used to install my charts as the current one has some issues https://github.com/k3s-io/helm-controller/issues/77  that I hope are addressed in a the newer version

This is related to https://github.com/k3s-io/helm-controller/issues/65 . 

I'm willing to document this once I know.

**Comment by ibrokethecloud** [comment]
The klipper-helm image can be overridden using the `jobImage` field in the HelmChartSpec

https://github.com/k3s-io/helm-controller/blob/master/pkg/apis/helm.cattle.io/v1/types.go#L29

**Comment by ieugen** [comment]
Thank you @ibrokethecloud .
That worked nicely and I was able to move forward. 
Closing this issue and hopefully someone will merge my PR.
