### ISSUE TITLE
Add support for self-signed SSL certificates / adding a trusted CA to the jobs images

### ISSUE THREAD

**Issue by Martin-Weiss** [k3s-io/helm-controller#89]
In case specifying the helm chart via 

chart: https://<helm-repo-server>/k8s-prod/cert-manager-v1.2.0.tgz

but use a self-signed certificate for that server - the helm chart download fails.

As a workaround we had to add the tgz via chartContent: but it would be much nicer if we could add a "trust this CA" or "trust the hosts CA" ..

Or is there any other way how we could address this "download helm charts from external HTTPS source or even from a registry with authentication"?

**Comment by brandond** [comment]
Fixed in https://github.com/k3s-io/helm-controller/pull/137

**Comment by orymate** [comment]
it seems like we need this one too to make it work k3s-io/klipper-helm#46

**Comment by brandond** [comment]
Not fixed; I forgot to push the correct commit from my local branch to github before merging the PR.
